### ISSUE TITLE
Build fails when using newer version of node.js

### ISSUE THREAD

**Issue by yyoon** [vanadium/reader#30]
@jxson 

I tried building the reader web project from my Macbook yesterday, but it kept producing some weird errors when npm tried to install `proxy` package.

It turns out it builds fine with the `node`, `npm` installed with `jiri profile install nodejs` command.
Maybe the vanadium version of node should take precedence over the system installed node?

**Comment by jxson** [comment]
It should work with with both, I can look into it. What versions of node and npm are you running on your laptop (you can grab them quickly with `node -v && npm -v`)?

**Comment by yyoon** [comment]
Here are the versions:
node: v4.1.1
npm: v2.14.4
